### ISSUE TITLE
Investigar relación entre excel-UML

### ISSUE THREAD

**Issue by fraagucan2** [EGC-GESTIONPROGRAMA-1718/program-manager-wpp#13]
Uno de los problemas a los que nos encontramos es cómo guardar el Google Sheet en la base de datos. Habría que investigar la equivalencia entre los campos del excel que tomamos como partida para convertirlo en una hoja de Google Sheet y los campos de las entidades de la base de datos.

**Comment by fraagucan2** [comment]
He encontrado incongruencias entre el modelo de la base de datos que tenemos y los excels (programme-pre y programme-main) y en una reunión con @juanrr950 hemos llegado a los siguientes acuerdos en cuanto al modelo de dominio:
- Entidad "Slot": unificar las propiedades "timeStart" y "timeEnd" en una sola llamada "time" que sea varChar, para evitar complicaciones con el casteo de tipo date como estaba anteriormente.
- Entidad "TalkGroup": que las propiedades "chair","URL" y "room" puedan ser nulas y añadir la propiedad "code" de tipo varChar.
- Entidad "Talk": eliminar las propiedades "timeEnd","eventt" y "code" y añadir una propiedad que sea "timming" de tipo varChar.

**Comment by fraagucan2** [comment]
@juanrr950 ponte en contacto con el grupo de integración para que lleven a cabo los cambios.

**Comment by juanrr950** [comment]
De acuerdo queda soluicionada está incidendia y abro una nueva para comunicar a integración los cambios
