### ISSUE TITLE
Construcción del proyecto en Travis

### ISSUE THREAD

**Issue by ordomedina** [EGC-GESTIONPROGRAMA-1718/program-manager-wpp#16]
Falla la construcción del proyecto en Travis. 
El error está relacionado con que Travis por defecto ejecuta los tests con phpunit, y no tenemos ninguno implementado.

**Comment by fraagucan2** [comment]
Cuando se haga merge a master el error de build en travis se solucionará. Para solucionarlo he añadido PHPUnit y he creado tests que siempre dan positivos (provisionalmente).
