### ISSUE TITLE
Implementar generador de ticker para programa

### ISSUE THREAD

**Issue by fraagucan2** [EGC-GESTIONPROGRAMA-1718/program-manager-wpp#17]
Hasta el momento el número de versión del programa se añade de forma manual. Lo ideal es que se implemente un método que genere automáticamente el número de la versión.

**Comment by juanrr950** [comment]
Lo ideal para eso creo que sería que cada vez que se le de a guardar que se le diga tambien si crear una versión mnueva o machacar alguna versión existente. Por lo que conviene primero resolver las issues que impiden ejecutar el código.

ademas mas que un ticker aleatorio yo veo que lo suyo es números correlativos pa saber  el orden de las versiones

**Comment by fraagucan2** [comment]
De momento vamos a optar por guardar en el número de versión el ID del programa.
