### ISSUE TITLE
Pagina Programa desaparecida

### ISSUE THREAD

**Issue by juanrr950** [EGC-GESTIONPROGRAMA-1718/program-manager-wpp#2]
En codigio herededao está el plugin instalado, pero no aparece la página de programa que genera como en la web de SPLC. Por lo que hay que encontrar la forma de como crear una página para que el plugin la capte y genere ahí el HTML del programa

**Comment by fraagucan2** [comment]
Supongo que eso será trabajo del grupo de Gestión de visualización de programa

**Comment by juanrr950** [comment]
de acuerdo, la cierro, añado que hemos encontrar que para que poder visualizar el programa en una página del blog hay que añadir uno de los shortcode especificados en settings, pero posteriormente da un error de carga del archivo y debido a la falta de documentación del plugin existen, vamos a comenzar a cambiar el formato de la hoja de calculo a google sheet
