### ISSUE TITLE
Error al ejecutar el código de lectura de Google Sheet en una máquina diferente

### ISSUE THREAD

**Issue by juanrr950** [EGC-GESTIONPROGRAMA-1718/program-manager-wpp#20]
Al ejecutar en una maquina diferente de la que se aha desarrollado el código de lectura de Google Sheet aparece el siguiente error:

MacBook-Pro-de-Juan:program-manager-wpp juanrr$ php pam.php

Fatal error: Uncaught Google_Service_Exception: {
  "error": {
    "code": 403,
    "message": "The caller does not have permission",
    "errors": [
      {
        "message": "The caller does not have permission",
        "domain": "global",
        "reason": "forbidden"
      }
    ],
    "status": "PERMISSION_DENIED"
  }
}
 in /Users/juanrr/git/program-manager-wpp/vendor/google/apiclient/src/Google/Http/REST.php:118
Stack trace:
#0 /Users/juanrr/git/program-manager-wpp/vendor/google/apiclient/src/Google/Http/REST.php(94): Google_Http_REST::decodeHttpResponse(Object(GuzzleHttp\Psr7\Response), Object(GuzzleHttp\Psr7\Request), 'Google_Service_...')
#1 /Users/juanrr/git/program-manager-wpp/vendor/google/apiclient/src/Google/Task/Runner.php(176): Google_Http_REST::doExecute(Object(GuzzleHttp\Client), Object(GuzzleHttp\Psr7\Request), 'Google_Service_...')
#2 /Users/juanrr/git/program-manager-wpp/vendor/google/apiclient/src/Google/Http/REST.php(58): Google_Task_Runner->run()
#3 /Users/juanrr/git/program-manager-wpp/vendor/go in /Users/juanrr/git/program-manager-wpp/vendor/google/apiclient/src/Google/Http/REST.php on line 118
MacBook-Pro-de-Juan:program-manager-wpp juanrr$ 

Probablemente es un error con las credenciales de google

**Comment by fraagucan2** [comment]
Queda solucionado con el uso de la API key. #23
