### ISSUE TITLE
Error al integrar el API google sheet con Plugin Wordpress

### ISSUE THREAD

**Issue by juanrr950** [EGC-GESTIONPROGRAMA-1718/program-manager-wpp#21]
Se ha encontrado un error en el archivo quickstart.php, en las lineas 14-16. Salta un excepción especificada en esas líneas que comprueba que el código solo se ejecuta en consola.

Por lo que es necesario modificar este archivo para que el codigo pueda ser ejecutado desde el plugin de wordpress.

A continuación, la traza del error:
Fatal error: Uncaught exception 'Exception' with message 'This application must be run on the command line.' in /Applications/XAMPP/xamppfiles/htdocs/splc/wp-content/plugins/program-manager-wpp/quickstart.php:15 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/splc/wp-content/plugins/program-manager-wpp/process_program.php(4): include() #1 /Applications/XAMPP/xamppfiles/htdocs/splc/wp-content/plugins/program-manager-wpp/settings.php(2): require('/Applications/X...') #2 /Applications/XAMPP/xamppfiles/htdocs/splc/wp-content/plugins/program-manager-wpp/program-manager-wpp.php(11): require('/Applications/X...') #3 /Applications/XAMPP/xamppfiles/htdocs/splc/wp-settings.php(303): include_once('/Applications/X...') #4 /Applications/XAMPP/xamppfiles/htdocs/splc/wp-config.php(94): require_once('/Applications/X...') #5 /Applications/XAMPP/xamppfiles/htdocs/splc/wp-load.php(37): require_once('/Applications/X...') #6 /Applications/XAMPP/xamppfiles/htdocs/splc/wp-blog-header.php(13): require_once('/Applications/X...') #7 /Applica in /Applications/XAMPP/xamppfiles/htdocs/splc/wp-content/plugins/program-manager-wpp/quickstart.php on line 15

**Comment by fraagucan2** [comment]
Al parecer el código que tenemos es sólo ejecutable por consola de comandos y para ejecutarlo en una aplicación web debemos utilizar OAuth 2.0.

Fuente: https://developers.google.com/api-client-library/php/auth/web-app

**Comment by juanrr950** [comment]
El problema queda solucionado, al haber cambiado la forma de conexión, que solventada la incidencia
