### ISSUE TITLE
Implementar OAuth 2.0 para la API de Google Sheet

### ISSUE THREAD

**Issue by fraagucan2** [EGC-GESTIONPROGRAMA-1718/program-manager-wpp#23]
Nos hemos percatado que la aplicación que habiamos desarrollado de la lectura de la hoja de Google Sheet era sólo ejecutable a través de la consola de comandos y que para poder ejecutarla en la web debemos implementar OAuth 2.0.

**Comment by juanrr950** [comment]
Se ha cambidado el metodo de conexion OAuth2 por API Key. Queda resuelta la incidencia
