### ISSUE TITLE
Actulización Nombres Tablas Base de datos

### ISSUE THREAD

**Issue by juanrr950** [EGC-GESTIONPROGRAMA-1718/program-manager-wpp#24]
Se ha detectado en el archivo process_program.php que la sentencias sql del código no tienen los nombre de las tablas y las columnas coincidentes con la ultima versión del script que el equipo de integración nos pasó, por lo que es necesaria su actualización

**Comment by fraagucan2** [comment]
Solucionado y funcionando!
